version: '3.1'
services:
  kp-smart-home-server:
    image: kp-smart-home-server:1.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "5000:5000"
  database:
    image: thomseno/h2:1.4.200
    ports:
      - "9092:9092"
      - "8082:8082"
    volumes:
     - "/h2-data:/h2-data"
    environment:
      - "name=h2"
